#!/usr/bin/ruby
require 'pp'
require File.dirname(__FILE__) + '/../config/environment'
Dir['app/models/**/*rb'].each {|f| require f}
pp Dir['/tmp/ruby_sess*'].collect do |file|
  [file, Marshal.load(File.read(file))]
end
